# Generated by Django 5.0.6 on 2024-06-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
            ],
        ),
    ]
