# Generated by Django 5.0.6 on 2024-06-26 04:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_criacao_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ('turma', 'data_de_inscricao'), 'verbose_name': 'Matricula',
                     'verbose_name_plural': 'Matriculas'},
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('usuario', 'turma')},
        ),
    ]
